<footer class="page-footer ${reportColor} lighten-4">
    <div class="footer-copyright ${reportColor} lighten-1">
        <div class="container">
            Happy Reporting!
            <a class="white-text text-lighten-4 right" href="http://reportbuilderjava.rajatthareja.com">Generated by Report Builder</a>
        </div>
    </div>
</footer>