<footer class="page-footer brown lighten-4">
    <div class="footer-copyright brown lighten-1">
        <div class="container">
            Happy Reporting!
            <a class="white-text text-lighten-4 right" href="http://reportbuilderjava.rajatthareja.com">Generated by Report Builder</a>
        </div>
    </div>
</footer>